sudo: required
language: rust
cache: cargo
script:
  - cargo clean
  - cargo build
  - cargo test
branches:
  only:
    - master
os:
  - linux
  - windows
  - osx
rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - os: "linux"
      addons:
        apt:
          packages:
            - libssl-dev
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

after_success: |
  if [[  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --skip-clean -v --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi