name: Code Coverage

on:
  push:
    branches: [master]
  pull_request:

jobs:
  codecov:      
    name: Run code coverage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
     
    - name: Run tarpaulin
      run: |
        curl -L https://github.com/xd009642/tarpaulin/releases/download/0.14.2/cargo-tarpaulin-0.14.2-travis.tar.gz > tarpaulin.tar.gz
        tar -xvzf tarpaulin.tar.gz
        ./cargo-tarpaulin tarpaulin -v --out Xml 
        
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
